### ISSUE TITLE
Module Info for Lmod

### ISSUE THREAD

**Issue by swien** [RRZE-HPC/MachineState#26]
The module information does only work with TCL. It would be great if it will also work with lmod (written in lua).

**Comment by swien** [comment]
Etwas Äquivalentes wäre bei lmod vermutlich `modulel -t spider 2>&1`, vielleicht aber auch `module -t list 2>&1`

**Comment by TomTheBear** [comment]
Please test the linked commit or PR https://github.com/RRZE-HPC/MachineState/pull/27 . With the PR, no config change should be required, it checks the environment variable `LMOD_CMD`.
