### ISSUE TITLE
macOS support?

### ISSUE THREAD

**Issue by boegel** [RRZE-HPC/MachineState#3]
Is there any interest in adding support for macOS?

I gave it a quick shot on my laptop (using 990194ff9de7cea7510e92eeb046ea2a9fa311ea) and it died horribly, probably because it assumes Linux as OS?

```
$ ./machinestate.py
Traceback (most recent call last):
  File "./machinestate.py", line 2610, in <module>
    main()
  File "./machinestate.py", line 2571, in main
    mstate.generate()
  File "./machinestate.py", line 903, in generate
    raise exce
  File "./machinestate.py", line 897, in generate
    cls = cltype(extended=self.extended, anonymous=self.anonymous, **clargs)
  File "./machinestate.py", line 1486, in __init__
    base = pjoin("/sys/fs/cgroup/cpuset", cset.strip("/"))
AttributeError: 'NoneType' object has no attribute 'strip'
```

**Comment by TomTheBear** [comment]
The error is independent on the OS, I didn't check the return value. I'll fix that.

When it comes to macOS, the question is, where do I get the information from. There is no procfs or sysfs. I'm not that deep in system stuff on macOS to know the other locations (if any). I'm confident that I can remove all runtime errors on macOS but does it gather enough information to get the whole picture?

I could add functionality to detect the OS that can be used in the code afterwards.  Would that help to integrate macOS support?

**Comment by boegel** [comment]
I think it would definitely be useful to detect the OS and discriminate between Linux and macOS.

Gathering system information on macOS is typically done via the `sysctl` command, see https://developer.apple.com/library/archive/documentation/System/Conceptual/ManPages_iPhoneOS/man3/sysctl.3.html, which is also what we use in `archspec` (see https://github.com/archspec/archspec/blob/95c2b1459fa02a29de367cba97562672ef953a9f/archspec/cpu/detect.py#L88)

**Comment by TomTheBear** [comment]
A OS detection is definitely useful.

Thanks for the hint with `sysctl`. I also saw `systemstats` which seems to print out useful information.

**Comment by TomTheBear** [comment]
See https://github.com/RRZE-HPC/MachineState/pull/4
